language: php
sudo: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/phpunit --coverage-clover build/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --diff --dry-run --using-cache=no; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then php vendor/bin/php-coveralls -v -x build/clover.xml -o build/clover.json; fi

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "dCyeBctSqDq6FcyS3MH+seIz/K9+AsUsgArP14OjWvGhkiupsBzgRmsJPO66X79jXTCkFEglgGYLeGQUJCnu1k9ERBJDVJV9QtHW1ChNPi5gL6+ZY+/lsVqAhKB24ATV7cGaqB4s98C3zDeR4l+8iJG7A9L8Kvupx7oLjOnSPAW2DNZ51vW4kCmMIVRG/DlPGMKXsILw4PnTUbReRJszNA9Hl0aMbtUJy709oeBToeFKVyiFaK+5XVi8L4yb1kkB7qftYJuHgkOfjT1kXs0k/O8orlTJ7BHiEGoxEbHncDZL2V99NDU2FINHRDhjiJwQEB6wG8yD6KtyzABPFZr53DYsimUDcoePJf5w1kUItdzH6Vu9XVNNi0I4BTHwtzzIn4p4LiMSnm063anUsQrkf1dpEHJ/esqaRahUqLJIIWsiGnp+P+RiEnf1wVYJJLsyLM/UL6cVrJYZCbliUB1yCofxF0TaAQ1pnPqBxMU9uvizWetCZjFkX4+O/ZfFbry8MDnS6ukdzCw8Fu1Kw0ebTcf7Cl4ZJ9HN2snlKc/hZDi8x27iytrg958eovdc/U7jN34F8X31uhNq+T1CfDI60iEFo/iCo3IWliF3++S6aU0mKNXupplBqExEblGDfRPNlPseGG7rYr1jUZbpdPHUzaCadKsWvhgk95yw9+bTNcQ="
